### PR TITLE
Update to Mist 0.10.0

### PR DESCRIPTION
**Pull request by rushsteve1**
Updated to Mist 0.10.0 from Upstream.
A PR to check with build bot.

### CODE REVIEW

**Comment by rushsteve1** [comment]
bot, build

**Comment by rushsteve1** [comment]
bot, build

**Comment by barthalion** [comment]
FYI, there are problems with GitHub integration. The build failed, you can read the logs here: https://flathub.org/builds/#/builders/2/builds/723

**Comment by rushsteve1** [comment]
I know, but thank you. I fixed the issue and wanted it to build again.

**Pull request merged**
